environment:
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\Scripts\\pip install -e ."
  - "%PYTHON%\\Scripts\\pip install -r tools\\requirements.txt"

build: off

test_script:
  - "%PYTHON%\\Scripts\\pytest"
